### ISSUE TITLE
Latest iotv version: 

### ISSUE THREAD

**Issue by wpiotrw** [e2iplayer/e2iplayer#2]
Hello

Wile trying to open some streams - next episodes of tv series,  for example from serialener.pl host, there is an error:

- Application/vnd.ms-sstr+xml decoder
-  your gstreamer installation is missing a plugin. Code 12

Some other episodes are opening without any issues

**Comment by e2iplayer** [comment]
https://gitlab.com/iptvplayer-for-e2/iptvplayer-for-e2/
